### PR TITLE
Refactor of CSharp

### PR DESCRIPTION
**Pull request by Maledong**
1) Add `Async` methods.
2) Remove uesless variables, codes.
3) Remove ConsoleApp and use UnitTest instead.
4) Add README.md instead.

### CODE REVIEW

**Comment by lionsoul2014** [comment]
@RocherKong C#的，瞧下

**Comment by RocherKong** [comment]
嗯，有空我重新整理下代码

**Comment by RocherKong** [comment]
@Maledong ok,I'll reorganize the code when I'm free.

**Comment by Maledong** [comment]
Since the C#'s style is something like Java. So I've changed them.
Thanks for reviewing.

**Comment by Maledong** [comment]
Since there's a missing of benchmark test with a unit test. I've added for that.
Besides, I've also normalized the style of C# from Java.
If necessary, plz merge them together.

**Comment by RocherKong** [comment]
@lionsoul2014 I have just reviewed the code. This modification is only an adjustment to the code format and naming, and has added the standard test. There is no change to the core code, and all can be merged.

**Pull request merged**
